"use client";

import Providers from "@/app/providers";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Loja",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
