import Header from "@/components/Header";
import Providers from "../../providers";
import GlobalStyles from "@/styles/global";
import StyledComponentsRegistry from "@/app/registry";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
      <ToastContainer
          position="top-right"
          theme="colored"
          autoClose={4000}
          hideProgressBar
        />
        <StyledComponentsRegistry>

          <Providers>
            <GlobalStyles />
            <Header />
            {children}
          </Providers>

        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
